apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fider-helm-chart.fullname" . }}
  labels:
  {{- include "fider-helm-chart.labels" . | nindent 4 }}
data:
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ printf "postgres://%s:%s@%s:%s/%s?sslmode=disable" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (printf "%s-postgresql-headless.%s.svc.cluster.local" .Release.Name .Release.Namespace) ( .Values.postgresql.service.port | toString ) .Values.postgresql.postgresqlDatabase | b64enc }}
  {{- end }}
  {{- if eq .Values.fider.email.service "mailgun" }}
  EMAIL_MAILGUN_API: {{ required "No mailgun api key provided" .Values.fider.email.mailgun.apiKey | b64enc }}
  {{- else if eq .Values.fider.email.service "smtp" }}
  EMAIL_SMTP_USERNAME: {{ required "No SMTP username provided" .Values.fider.email.smtp.username | b64enc }}
  EMAIL_SMTP_PASSWORD: {{ required "No SMTP password provided" .Values.fider.email.smtp.password | b64enc }}
  {{- end }}
  JWT_SECRET: {{ .Values.fider.jwtSecret | default (randAlphaNum 64) | b64enc}}